version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    working_directory: ~/tea
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          PGHOST: localhost
          PGUSER: tea
          RAILS_ENV: test
      - image: postgres:13.2
        environment:
          POSTGRES_USER: tea
          POSTGRES_DB: tea_test
          POSTGRES_PASSWORD:
    steps:
      - checkout
      - run:
          name: tea
          command: bundle -v
      - ruby/bundle-install
      - checkout
      - run: gem install bundler
      - run: bundle install --path vendor/bundle
      - run: bundle exec rake db:setup
      - run: bundle exec rspec